// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package postgres

import (
	"time"

	"github.com/google/uuid"
	null "gopkg.in/guregu/null.v4"
)

type Image struct {
	ID        uuid.UUID
	Title     null.String
	FileHash  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	FullName     string
	RoleID       int32
	PasswordHash string
	PictureID    uuid.NullUUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    null.Time
}
