// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckImageExists(ctx context.Context, id uuid.UUID) (bool, error)
	CheckImageHashExists(ctx context.Context, fileHash string) (bool, error)
	DeleteAllUsers(ctx context.Context) error
	DeleteImage(ctx context.Context, id uuid.UUID) error
	GetAllImages(ctx context.Context, imageIds []uuid.UUID) ([]GetAllImagesRow, error)
	GetAllUsers(ctx context.Context, userIds []uuid.UUID) ([]GetAllUsersRow, error)
	GetImageById(ctx context.Context, id uuid.UUID) (Image, error)
	GetManyImages(ctx context.Context, arg GetManyImagesParams) ([]GetManyImagesRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, userID uuid.UUID) (User, error)
	HardDeleteUser(ctx context.Context, userID uuid.UUID) error
	InsertOrUpdateImage(ctx context.Context, arg InsertOrUpdateImageParams) error
	InsertOrUpdateUser(ctx context.Context, arg InsertOrUpdateUserParams) error
	SoftDeleteUser(ctx context.Context, userID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
