// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/thanishsid/goserver/domain"
)

type CompleteRegistrationInput struct {
	Token     string  `json:"token"`
	Username  string  `json:"username"`
	Password  string  `json:"password"`
	PictureID *string `json:"pictureId"`
}

type Message struct {
	Message string `json:"message"`
}

type MyInfo struct {
	Account *domain.User    `json:"account"`
	Session *domain.Session `json:"session"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage bool   `json:"hasNextPage"`
}

type Role struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type StartRegistrationInput struct {
	FullName    string `json:"fullName"`
	Email       string `json:"email"`
	CallbackURL string `json:"callbackUrl"`
}

type StartUserCreationInput struct {
	FullName    string `json:"fullName"`
	Email       string `json:"email"`
	Role        string `json:"role"`
	CallbackURL string `json:"callbackUrl"`
}

type UpdateProfileInput struct {
	Username  string  `json:"username"`
	FullName  string  `json:"fullName"`
	PictureID *string `json:"pictureId"`
}

type UserCollection struct {
	Nodes    []*domain.User `json:"nodes"`
	Edges    []*UserEdge    `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type UserEdge struct {
	Cursor string       `json:"cursor"`
	Node   *domain.User `json:"node"`
}
