services:
  postgres:
    image: postgres:14-alpine3.16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  session:
    image: redis:7.0.3-alpine3.16
    ports:
      - 6789:6789
  imgproxy:
    image: darthsim/imgproxy:latest
    ports:
      - 9000:9000
    volumes:
      - ~/dev/media/images:/mnt/images
    environment:
      - IMGPROXY_MAX_SRC_RESOLUTION=50
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
      - IMGPROXY_ENFORCE_WEBP=true
      - IMGPROXY_ENABLE_AVIF_DETECTION=true
      - IMGPROXY_ENFORCE_AVIF=true
      - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/mnt/images
      - IMGPROXY_AVIF_SPEED=8
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - session
      - search
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/wait-for.sh",
        "session:6379",
        "--",
        "/app/wait-for.sh",
        "imgproxy:9000",
        "--",
        "/app/start.sh"
      ]
    command: "/app/main"
