// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"

	"github.com/google/uuid"
	null "gopkg.in/guregu/null.v4"
)

type Image struct {
	ID        uuid.UUID
	Title     null.String
	FileHash  []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Role struct {
	ID   string
	Name string
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	FullName     string
	Role         string
	PasswordHash string
	PictureID    uuid.NullUUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    null.Time
	SearchIndex  interface{}
}

type Video struct {
	ID          uuid.UUID
	Title       null.String
	FileHash    []byte
	ThumbnailID uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
