// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckImageExists(ctx context.Context, id uuid.UUID) (bool, error)
	CheckImageHashExists(ctx context.Context, fileHash []byte) (bool, error)
	DeleteImage(ctx context.Context, id uuid.UUID) error
	DeleteRole(ctx context.Context, id string) error
	GetAllImagesInIDS(ctx context.Context, imageIds []uuid.UUID) ([]GetAllImagesInIDSRow, error)
	GetAllRoles(ctx context.Context) ([]Role, error)
	GetAllUsersInIDS(ctx context.Context, userIds []uuid.UUID) ([]GetAllUsersInIDSRow, error)
	GetImageById(ctx context.Context, id uuid.UUID) (Image, error)
	GetManyImages(ctx context.Context, arg GetManyImagesParams) ([]GetManyImagesRow, error)
	GetManyUsers(ctx context.Context, arg GetManyUsersParams) ([]GetManyUsersRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, userID uuid.UUID) (GetUserByIdRow, error)
	HardDeleteUser(ctx context.Context, userID uuid.UUID) error
	InsertOrUpdateImage(ctx context.Context, arg InsertOrUpdateImageParams) error
	InsertOrUpdateRoles(ctx context.Context, arg InsertOrUpdateRolesParams) error
	InsertOrUpdateUser(ctx context.Context, arg InsertOrUpdateUserParams) error
	SoftDeleteUser(ctx context.Context, userID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
